markdown: kramdown
permalink: /articles/:title
source: site
destination: site-build
exclude:
- README.md
- Rakefile
navigation:
- text: Articles
  class: page_white_stack
  url: articles/
- text: FAQ
  class: help
  url: faq/
- text: Feedback
  class: comments
  url: feedback/